# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ChangeUsrname.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ChangeUsrname(object):
    def setupUi(self, ChangeUsrname):
        ChangeUsrname.setObjectName("ChangeUsrname")
        ChangeUsrname.resize(600, 240)
        ChangeUsrname.setMinimumSize(QtCore.QSize(600, 240))
        ChangeUsrname.setMaximumSize(QtCore.QSize(600, 240))
        ChangeUsrname.setStyleSheet("background-color: rgb(255, 170, 173);")
        self.usrname_let = QtWidgets.QLineEdit(ChangeUsrname)
        self.usrname_let.setGeometry(QtCore.QRect(240, 90, 280, 40))
        font = QtGui.QFont()
        font.setFamily("方正小标宋简体")
        font.setPointSize(10)
        self.usrname_let.setFont(font)
        self.usrname_let.setObjectName("usrname_let")
        self.text_lbl = QtWidgets.QLabel(ChangeUsrname)
        self.text_lbl.setGeometry(QtCore.QRect(60, 100, 171, 20))
        font = QtGui.QFont()
        font.setFamily("方正小标宋简体")
        font.setPointSize(10)
        self.text_lbl.setFont(font)
        self.text_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.text_lbl.setObjectName("text_lbl")
        self.confirm_btn = QtWidgets.QPushButton(ChangeUsrname)
        self.confirm_btn.setGeometry(QtCore.QRect(300, 170, 100, 40))
        font = QtGui.QFont()
        font.setFamily("方正小标宋简体")
        font.setPointSize(10)
        self.confirm_btn.setFont(font)
        self.confirm_btn.setObjectName("confirm_btn")

        self.retranslateUi(ChangeUsrname)
        QtCore.QMetaObject.connectSlotsByName(ChangeUsrname)

    def retranslateUi(self, ChangeUsrname):
        _translate = QtCore.QCoreApplication.translate
        ChangeUsrname.setWindowTitle(_translate("ChangeUsrname", "修改用户名"))
        self.text_lbl.setText(_translate("ChangeUsrname", "请输入新用户名"))
        self.confirm_btn.setText(_translate("ChangeUsrname", "确认"))
        self.confirm_btn.setShortcut(_translate("ChangeUsrname", "Return"))
