# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\UISRC\CleanPwd.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CleanPwd(object):
    def setupUi(self, CleanPwd):
        CleanPwd.setObjectName("CleanPwd")
        CleanPwd.resize(500, 350)
        CleanPwd.setMinimumSize(QtCore.QSize(500, 350))
        CleanPwd.setMaximumSize(QtCore.QSize(500, 350))
        CleanPwd.setStyleSheet("background-color: rgb(255, 170, 173);")
        self.questionAns_let = QtWidgets.QLineEdit(CleanPwd)
        self.questionAns_let.setGeometry(QtCore.QRect(170, 210, 270, 40))
        font = QtGui.QFont()
        font.setFamily("方正小标宋简体")
        font.setPointSize(10)
        self.questionAns_let.setFont(font)
        self.questionAns_let.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.questionAns_let.setObjectName("questionAns_let")
        self.confirm_btn = QtWidgets.QPushButton(CleanPwd)
        self.confirm_btn.setGeometry(QtCore.QRect(250, 270, 111, 51))
        font = QtGui.QFont()
        font.setFamily("方正小标宋简体")
        font.setPointSize(10)
        self.confirm_btn.setFont(font)
        self.confirm_btn.setAutoDefault(False)
        self.confirm_btn.setDefault(False)
        self.confirm_btn.setObjectName("confirm_btn")
        self.usrname = QtWidgets.QLabel(CleanPwd)
        self.usrname.setGeometry(QtCore.QRect(70, 60, 91, 41))
        font = QtGui.QFont()
        font.setFamily("方正小标宋简体")
        font.setPointSize(10)
        self.usrname.setFont(font)
        self.usrname.setTextFormat(QtCore.Qt.AutoText)
        self.usrname.setAlignment(QtCore.Qt.AlignCenter)
        self.usrname.setObjectName("usrname")
        self.usr_let = QtWidgets.QLineEdit(CleanPwd)
        self.usr_let.setGeometry(QtCore.QRect(170, 60, 270, 40))
        font = QtGui.QFont()
        font.setFamily("方正小标宋简体")
        font.setPointSize(10)
        self.usr_let.setFont(font)
        self.usr_let.setReadOnly(False)
        self.usr_let.setObjectName("usr_let")
        self.questionAns = QtWidgets.QLabel(CleanPwd)
        self.questionAns.setGeometry(QtCore.QRect(70, 210, 91, 41))
        font = QtGui.QFont()
        font.setFamily("方正小标宋简体")
        font.setPointSize(10)
        self.questionAns.setFont(font)
        self.questionAns.setAlignment(QtCore.Qt.AlignCenter)
        self.questionAns.setObjectName("questionAns")
        self.question_let = QtWidgets.QLineEdit(CleanPwd)
        self.question_let.setGeometry(QtCore.QRect(170, 140, 270, 40))
        font = QtGui.QFont()
        font.setFamily("方正小标宋简体")
        font.setPointSize(10)
        self.question_let.setFont(font)
        self.question_let.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.question_let.setReadOnly(True)
        self.question_let.setObjectName("question_let")
        self.questionAns_2 = QtWidgets.QLabel(CleanPwd)
        self.questionAns_2.setGeometry(QtCore.QRect(50, 140, 111, 41))
        font = QtGui.QFont()
        font.setFamily("方正小标宋简体")
        font.setPointSize(10)
        self.questionAns_2.setFont(font)
        self.questionAns_2.setAlignment(QtCore.Qt.AlignCenter)
        self.questionAns_2.setObjectName("questionAns_2")
        self.usr_hint = QtWidgets.QLabel(CleanPwd)
        self.usr_hint.setGeometry(QtCore.QRect(170, 100, 270, 40))
        font = QtGui.QFont()
        font.setFamily("方正小标宋简体")
        self.usr_hint.setFont(font)
        self.usr_hint.setText("")
        self.usr_hint.setObjectName("usr_hint")

        self.retranslateUi(CleanPwd)
        QtCore.QMetaObject.connectSlotsByName(CleanPwd)

    def retranslateUi(self, CleanPwd):
        _translate = QtCore.QCoreApplication.translate
        CleanPwd.setWindowTitle(_translate("CleanPwd", "重置密码"))
        self.confirm_btn.setText(_translate("CleanPwd", "确认"))
        self.confirm_btn.setShortcut(_translate("CleanPwd", "Return"))
        self.usrname.setText(_translate("CleanPwd", "<html><head/><body><p>用户名</p></body></html>"))
        self.questionAns.setText(_translate("CleanPwd", "<html><head/><body><p>问题答案</p></body></html>"))
        self.questionAns_2.setText(_translate("CleanPwd", "<html><head/><body><p>您的密保问题</p></body></html>"))
