# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\UISRC\JudgementQ.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_JudgementQ(object):
    def setupUi(self, JudgementQ):
        JudgementQ.setObjectName("JudgementQ")
        JudgementQ.resize(1000, 618)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(JudgementQ.sizePolicy().hasHeightForWidth())
        JudgementQ.setSizePolicy(sizePolicy)
        JudgementQ.setMinimumSize(QtCore.QSize(1000, 618))
        JudgementQ.setMaximumSize(QtCore.QSize(1000, 618))
        JudgementQ.setStyleSheet("background-color: rgb(255, 165, 171);")
        self.next_btn = QtWidgets.QPushButton(JudgementQ)
        self.next_btn.setGeometry(QtCore.QRect(890, 220, 60, 60))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.next_btn.setFont(font)
        self.next_btn.setObjectName("next_btn")
        self.question_text = QtWidgets.QTextEdit(JudgementQ)
        self.question_text.setGeometry(QtCore.QRect(150, 80, 700, 300))
        font = QtGui.QFont()
        font.setFamily("方正小标宋简体")
        font.setPointSize(10)
        self.question_text.setFont(font)
        self.question_text.setReadOnly(True)
        self.question_text.setObjectName("question_text")
        self.previous_btn = QtWidgets.QPushButton(JudgementQ)
        self.previous_btn.setGeometry(QtCore.QRect(50, 220, 60, 60))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.previous_btn.setFont(font)
        self.previous_btn.setObjectName("previous_btn")
        self.True_btn = QtWidgets.QPushButton(JudgementQ)
        self.True_btn.setGeometry(QtCore.QRect(240, 430, 90, 40))
        font = QtGui.QFont()
        font.setFamily("方正小标宋简体")
        font.setPointSize(10)
        self.True_btn.setFont(font)
        self.True_btn.setObjectName("True_btn")
        self.False_btn = QtWidgets.QPushButton(JudgementQ)
        self.False_btn.setGeometry(QtCore.QRect(670, 430, 90, 40))
        font = QtGui.QFont()
        font.setFamily("方正小标宋简体")
        font.setPointSize(10)
        self.False_btn.setFont(font)
        self.False_btn.setObjectName("False_btn")
        self.index_lbl = QtWidgets.QLabel(JudgementQ)
        self.index_lbl.setGeometry(QtCore.QRect(400, 580, 200, 30))
        font = QtGui.QFont()
        font.setFamily("方正小标宋简体")
        font.setPointSize(10)
        self.index_lbl.setFont(font)
        self.index_lbl.setText("")
        self.index_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.index_lbl.setObjectName("index_lbl")

        self.retranslateUi(JudgementQ)
        QtCore.QMetaObject.connectSlotsByName(JudgementQ)

    def retranslateUi(self, JudgementQ):
        _translate = QtCore.QCoreApplication.translate
        JudgementQ.setWindowTitle(_translate("JudgementQ", "正在答题"))
        self.next_btn.setText(_translate("JudgementQ", "⇨"))
        self.next_btn.setShortcut(_translate("JudgementQ", "Right"))
        self.previous_btn.setText(_translate("JudgementQ", "⇦"))
        self.previous_btn.setShortcut(_translate("JudgementQ", "Left"))
        self.True_btn.setText(_translate("JudgementQ", "√(T)"))
        self.False_btn.setText(_translate("JudgementQ", "×(F)"))
