# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\MessageBox.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MessageBox(object):
    def setupUi(self, MessageBox):
        MessageBox.setObjectName("MessageBox")
        MessageBox.resize(420, 200)
        MessageBox.setMinimumSize(QtCore.QSize(420, 200))
        MessageBox.setMaximumSize(QtCore.QSize(420, 200))
        MessageBox.setWindowTitle("")
        MessageBox.setStyleSheet("background-color: rgb(255, 170, 173);")
        self.confirm_btn = QtWidgets.QPushButton(MessageBox)
        self.confirm_btn.setGeometry(QtCore.QRect(270, 140, 90, 40))
        font = QtGui.QFont()
        font.setFamily("方正小标宋简体")
        font.setPointSize(9)
        self.confirm_btn.setFont(font)
        self.confirm_btn.setObjectName("confirm_btn")
        self.text_lbl = QtWidgets.QLabel(MessageBox)
        self.text_lbl.setGeometry(QtCore.QRect(30, 40, 360, 80))
        font = QtGui.QFont()
        font.setFamily("方正小标宋简体")
        font.setPointSize(10)
        self.text_lbl.setFont(font)
        self.text_lbl.setText("")
        self.text_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.text_lbl.setObjectName("text_lbl")

        self.retranslateUi(MessageBox)
        QtCore.QMetaObject.connectSlotsByName(MessageBox)

    def retranslateUi(self, MessageBox):
        _translate = QtCore.QCoreApplication.translate
        self.confirm_btn.setText(_translate("MessageBox", "确认"))
