# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\UISRC\ShortAnswerQ.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ShortAnswerQ(object):
    def setupUi(self, ShortAnswerQ):
        ShortAnswerQ.setObjectName("ShortAnswerQ")
        ShortAnswerQ.resize(1000, 618)
        ShortAnswerQ.setMinimumSize(QtCore.QSize(1000, 618))
        ShortAnswerQ.setMaximumSize(QtCore.QSize(1000, 618))
        ShortAnswerQ.setStyleSheet("background-color: rgb(255, 170, 173);")
        self.question_text = QtWidgets.QTextEdit(ShortAnswerQ)
        self.question_text.setGeometry(QtCore.QRect(150, 50, 700, 90))
        font = QtGui.QFont()
        font.setFamily("方正小标宋简体")
        font.setPointSize(10)
        self.question_text.setFont(font)
        self.question_text.setReadOnly(True)
        self.question_text.setObjectName("question_text")
        self.ansArea_text = QtWidgets.QTextEdit(ShortAnswerQ)
        self.ansArea_text.setGeometry(QtCore.QRect(130, 180, 350, 350))
        font = QtGui.QFont()
        font.setFamily("方正小标宋简体")
        font.setPointSize(10)
        self.ansArea_text.setFont(font)
        self.ansArea_text.setObjectName("ansArea_text")
        self.answer_text = QtWidgets.QTextEdit(ShortAnswerQ)
        self.answer_text.setGeometry(QtCore.QRect(510, 180, 350, 280))
        font = QtGui.QFont()
        font.setFamily("方正小标宋简体")
        font.setPointSize(10)
        self.answer_text.setFont(font)
        self.answer_text.setReadOnly(True)
        self.answer_text.setObjectName("answer_text")
        self.answer_btn = QtWidgets.QPushButton(ShortAnswerQ)
        self.answer_btn.setGeometry(QtCore.QRect(630, 480, 120, 50))
        font = QtGui.QFont()
        font.setFamily("方正小标宋简体")
        font.setPointSize(10)
        self.answer_btn.setFont(font)
        self.answer_btn.setStyleSheet("")
        self.answer_btn.setObjectName("answer_btn")
        self.next_btn = QtWidgets.QPushButton(ShortAnswerQ)
        self.next_btn.setGeometry(QtCore.QRect(890, 220, 60, 60))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.next_btn.setFont(font)
        self.next_btn.setObjectName("next_btn")
        self.previous_btn = QtWidgets.QPushButton(ShortAnswerQ)
        self.previous_btn.setGeometry(QtCore.QRect(50, 220, 60, 60))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.previous_btn.setFont(font)
        self.previous_btn.setObjectName("previous_btn")
        self.index_lbl = QtWidgets.QLabel(ShortAnswerQ)
        self.index_lbl.setGeometry(QtCore.QRect(400, 580, 200, 30))
        font = QtGui.QFont()
        font.setFamily("方正小标宋简体")
        font.setPointSize(10)
        self.index_lbl.setFont(font)
        self.index_lbl.setText("")
        self.index_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.index_lbl.setObjectName("index_lbl")
        self.ansArea_label = QtWidgets.QLabel(ShortAnswerQ)
        self.ansArea_label.setGeometry(QtCore.QRect(240, 540, 90, 40))
        font = QtGui.QFont()
        font.setFamily("方正小标宋简体")
        font.setPointSize(10)
        self.ansArea_label.setFont(font)
        self.ansArea_label.setAlignment(QtCore.Qt.AlignCenter)
        self.ansArea_label.setObjectName("ansArea_label")

        self.retranslateUi(ShortAnswerQ)
        QtCore.QMetaObject.connectSlotsByName(ShortAnswerQ)

    def retranslateUi(self, ShortAnswerQ):
        _translate = QtCore.QCoreApplication.translate
        ShortAnswerQ.setWindowTitle(_translate("ShortAnswerQ", "正在答题"))
        self.answer_btn.setText(_translate("ShortAnswerQ", "查看答案"))
        self.next_btn.setText(_translate("ShortAnswerQ", "⇨"))
        self.next_btn.setShortcut(_translate("ShortAnswerQ", "Right"))
        self.previous_btn.setText(_translate("ShortAnswerQ", "⇦"))
        self.previous_btn.setShortcut(_translate("ShortAnswerQ", "Left"))
        self.ansArea_label.setText(_translate("ShortAnswerQ", "作答区"))
