# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\UserCenter.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_UserCenter(object):
    def setupUi(self, UserCenter):
        UserCenter.setObjectName("UserCenter")
        UserCenter.resize(400, 550)
        UserCenter.setMinimumSize(QtCore.QSize(400, 550))
        UserCenter.setMaximumSize(QtCore.QSize(400, 550))
        UserCenter.setStyleSheet("background-color: rgb(255, 170, 173);")
        self.avatar_lbl = QtWidgets.QLabel(UserCenter)
        self.avatar_lbl.setGeometry(QtCore.QRect(125, 80, 150, 150))
        self.avatar_lbl.setMinimumSize(QtCore.QSize(150, 150))
        self.avatar_lbl.setMaximumSize(QtCore.QSize(150, 150))
        self.avatar_lbl.setText("")
        self.avatar_lbl.setObjectName("avatar_lbl")
        self.changeUname_btn = QtWidgets.QPushButton(UserCenter)
        self.changeUname_btn.setGeometry(QtCore.QRect(150, 380, 100, 40))
        font = QtGui.QFont()
        font.setFamily("方正小标宋简体")
        self.changeUname_btn.setFont(font)
        self.changeUname_btn.setObjectName("changeUname_btn")
        self.changePwd_btn = QtWidgets.QPushButton(UserCenter)
        self.changePwd_btn.setGeometry(QtCore.QRect(150, 460, 100, 40))
        font = QtGui.QFont()
        font.setFamily("方正小标宋简体")
        self.changePwd_btn.setFont(font)
        self.changePwd_btn.setObjectName("changePwd_btn")
        self.welcome_lbl = QtWidgets.QLabel(UserCenter)
        self.welcome_lbl.setGeometry(QtCore.QRect(80, 300, 240, 40))
        font = QtGui.QFont()
        font.setFamily("方正小标宋简体")
        font.setPointSize(10)
        self.welcome_lbl.setFont(font)
        self.welcome_lbl.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.welcome_lbl.setFocusPolicy(QtCore.Qt.NoFocus)
        self.welcome_lbl.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.welcome_lbl.setAutoFillBackground(False)
        self.welcome_lbl.setText("")
        self.welcome_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.welcome_lbl.setObjectName("welcome_lbl")

        self.retranslateUi(UserCenter)
        QtCore.QMetaObject.connectSlotsByName(UserCenter)

    def retranslateUi(self, UserCenter):
        _translate = QtCore.QCoreApplication.translate
        UserCenter.setWindowTitle(_translate("UserCenter", "个人中心"))
        self.changeUname_btn.setText(_translate("UserCenter", "修改用户名"))
        self.changePwd_btn.setText(_translate("UserCenter", "修改密码"))
